export default {
  ONE_PERSON: '1 Person',
  TWO_PERSONS: '2 Person',
  THREE_PERSONS: '3 Person',
  FOUR_PERSONS: '4 Person',
  FIVE_PERSONS: '5 Person',
  SIX_PERSONS: '6 Person',
  SEVEN_PERSONS: '7 Person',
  EIGHT_PERSONS: '8 Person',
  EXEC_SUITES: 'Executive Suite',
  OPEN_SPACE: 'Open Space',
  SMALL_CONFERENCE: 'Small Conference Room',
  MEDIUM_CONFERENCE: 'Medium Conference Room',
  LARGE_CONFERENCE: 'Large Conference Room',
  PHONE_ROOMS: 'Phone Rooms',
  ADA_PHONE_ROOMS: 'Accessible Phone Room',
  COPY_AREA: 'Copy Area',
  LOBBY_LOUNGE: 'Lobby / Lounge',
  LIBRARY_CAFE: 'Library / Cafe',
  DINING: 'Dining',
  KITCHEN: 'Kitchen',
  PACKAGE_ROOM: 'Package Room',
  MDF_ROOM: 'MDF Room',
  STORAGE: 'Storage',
  JANITORS_CLOSET: "Janitor's closet",
  SHOWER: 'Shower',
  BATHROOM: 'Bathroom',
  OTHER: 'Other',
  OTHER_SMALL: 'Other - Small'
}
